name: 빌드 및 배포

on: 
  push:
    branches: [ main ]

jobs: 
  build-docker-image: 
    runs-on: ubuntu-latest
    steps:
      - name: 원격 저장소에서 소스 복사
        uses: actions/checkout@v3 

      - name: 소스 파일을 docker image로 빌드
        run: docker build -t kimjihye0405/my-fastapi-whoami:latest .

      - name: 도커 허브에 로그인
        run: docker login -u kimjihye0405 -p ${{secrets.DOCKER_PASSWORD}}

      - name: 생성된 이미지를 도커 허브에 push
        run: docker push kimjihye0405/my-fastapi-whoami:latest
  
  deploy: 
    needs: build-docker-image
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo '이미지 배포 및 실행'
